In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline


##  ALL IMPORTANT
### Going to do a greast coding stuf

# READING THE DATA


In [68]:
df = pd.read_csv("../data/Training.csv")

df

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze                                prognosis  
0                     0                         Fungal infection  
1                     0                         Fungal infection  
2                     0                         Fungal infection  
3                     0                         Fungal infection  
4                     0                    

In [69]:
a = len(df["prognosis"].unique())

df.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

## No null data all values are filled correctly


# Just do train test split here 

In [4]:
from  sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
x = df.drop("prognosis", axis =1)

y = df["prognosis"]

In [ ]:
ecnoder = LabelEncoder()
ecnoder.fit(y)


y = ecnoder.transform(y)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=45)




In [6]:
from sklearn.datasets import make_classification

from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier

from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix



# create dictionay to save metrices


In [7]:
models = {
    "SVC": SVC(kernel="linear"),
    "RandomForestClassifier": RandomForestClassifier(n_estimators=100, random_state=42),
    "GradientBoostingClasifier": GradientBoostingClassifier(n_estimators=100, random_state=45),
    "KNeighbour": KNeighborsClassifier(n_neighbors=5, n_jobs=-1),
    "MultinomialDb":MultinomialNB(),

}

In [8]:

for model_name, model in models.items():
    model.fit(x_train, y_train)

    # test model

    print(model)

    y_test_pred = model.predict(x_test)

    print(accuracy_score(y_test, y_test_pred))

    print(confusion_matrix(y_test_pred, y_test))

    print("===============================\n\n")

    

SVC(kernel='linear')
1.0
[[23  0  0 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 0  0 22 ...  0  0  0]
 ...
 [ 0  0  0 ... 23  0  0]
 [ 0  0  0 ...  0 21  0]
 [ 0  0  0 ...  0  0 22]]


RandomForestClassifier(random_state=42)
1.0
[[23  0  0 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 0  0 22 ...  0  0  0]
 ...
 [ 0  0  0 ... 23  0  0]
 [ 0  0  0 ...  0 21  0]
 [ 0  0  0 ...  0  0 22]]


GradientBoostingClassifier(random_state=45)
1.0
[[23  0  0 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 0  0 22 ...  0  0  0]
 ...
 [ 0  0  0 ... 23  0  0]
 [ 0  0  0 ...  0 21  0]
 [ 0  0  0 ...  0  0 22]]


KNeighborsClassifier(n_jobs=-1)
1.0
[[23  0  0 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 0  0 22 ...  0  0  0]
 ...
 [ 0  0  0 ... 23  0  0]
 [ 0  0  0 ...  0 21  0]
 [ 0  0  0 ...  0  0 22]]


MultinomialNB()
1.0
[[23  0  0 ...  0  0  0]
 [ 0 26  0 ...  0  0  0]
 [ 0  0 22 ...  0  0  0]
 ...
 [ 0  0  0 ... 23  0  0]
 [ 0  0  0 ...  0 21  0]
 [ 0  0  0 ...  0  0 22]]




In [9]:
svc1 = SVC(kernel="linear")

svc1.fit(x_train,y_train)

y_pred= svc1.predict(x_test)

accuracy_score(y_test,y_pred)

1.0

In [ ]:

pickle.dump(svc1,open("../model/svc1.pkl", "wb"))


# Load the model

In [12]:
import pickle
svc = pickle.load(open("../model/svc1.pkl","rb"))

In [13]:

a = svc.predict(x_test.iloc[[5]])
print(a)

[33]


33

# Recommendation System And Predection

In [58]:
df_sym = pd.read_csv("../data/symtoms_df.csv")

df_sym

df_prec = pd.read_csv("../data/precautions_df.csv")

df_prec

df_workout = pd.read_csv("../data/workout_df.csv")

df_desc = pd.read_csv("../data/description.csv")

df_med = pd.read_csv("../data/medications.csv")
df_sym
df_diet = pd.read_csv("../data/diets.csv")


In [ ]:
import numpy

import pandas as pd

# Assuming your DataFrame is called df
# Combine all symptoms into one flat list
all_symptoms = pd.unique(df_sym[['Symptom_1', 'Symptom_2', 'Symptom_3','Symptom_4']].values.ravel())

# Create indexed dictionary
symptom_dict = {i: symptom for i, symptom in enumerate(all_symptoms)}

print(symptom_dict)






{0: 'itching', 1: ' skin_rash', 2: ' nodal_skin_eruptions', 3: ' dischromic _patches', 4: nan, 5: ' continuous_sneezing', 6: ' shivering', 7: ' chills', 8: ' watering_from_eyes', 9: ' stomach_pain', 10: ' acidity', 11: ' ulcers_on_tongue', 12: ' vomiting', 13: ' cough', 14: ' yellowish_skin', 15: ' nausea', 16: ' loss_of_appetite', 17: ' burning_micturition', 18: ' spotting_ urination', 19: ' abdominal_pain', 20: ' passage_of_gases', 21: ' indigestion', 22: ' muscle_wasting', 23: ' patches_in_throat', 24: ' high_fever', 25: ' extra_marital_contacts', 26: ' fatigue', 27: ' weight_loss', 28: ' restlessness', 29: ' lethargy', 30: ' irregular_sugar_level', 31: ' sunken_eyes', 32: ' dehydration', 33: ' diarrhoea', 34: ' breathlessness', 35: ' family_history', 36: ' headache', 37: ' chest_pain', 38: ' dizziness', 39: ' loss_of_balance', 40: ' lack_of_concentration', 41: ' blurred_and_distorted_vision', 42: ' excessive_hunger', 43: ' back_pain', 44: ' weakness_in_limbs', 45: ' neck_pain', 46:

In [36]:
# Get unique diseases from the 'Disease' column
unique_diseases = df_sym['Disease'].unique()

# Create dictionary with index as key and disease as value
disease_dict = {i: disease for i, disease in enumerate(unique_diseases)}

print(disease_dict)


{0: 'Fungal infection', 1: 'Allergy', 2: 'GERD', 3: 'Chronic cholestasis', 4: 'Drug Reaction', 5: 'Peptic ulcer diseae', 6: 'AIDS', 7: 'Diabetes ', 8: 'Gastroenteritis', 9: 'Bronchial Asthma', 10: 'Hypertension ', 11: 'Migraine', 12: 'Cervical spondylosis', 13: 'Paralysis (brain hemorrhage)', 14: 'Jaundice', 15: 'Malaria', 16: 'Chicken pox', 17: 'Dengue', 18: 'Typhoid', 19: 'hepatitis A', 20: 'Hepatitis B', 21: 'Hepatitis C', 22: 'Hepatitis D', 23: 'Hepatitis E', 24: 'Alcoholic hepatitis', 25: 'Tuberculosis', 26: 'Common Cold', 27: 'Pneumonia', 28: 'Dimorphic hemmorhoids(piles)', 29: 'Heart attack', 30: 'Varicose veins', 31: 'Hypothyroidism', 32: 'Hyperthyroidism', 33: 'Hypoglycemia', 34: 'Osteoarthristis', 35: 'Arthritis', 36: '(vertigo) Paroymsal  Positional Vertigo', 37: 'Acne', 38: 'Urinary tract infection', 39: 'Psoriasis', 40: 'Impetigo'}


In [61]:
symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

# helper funcitoon
def helper(dis):
    desc = df_desc[df_desc['Disease'] == dis]['Description']
    desc = " ".join([w for w in desc])

    pre = df_prec[df_prec['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = df_med[df_med['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = df_diet[df_diet['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = df_workout[df_workout['disease'] == dis] ['workout']


    return desc,pre,med,die,wrkout


# Model Prediction function
def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        input_vector[symptoms_dict[item]] = 1
    return diseases_list[svc.predict([input_vector])[0]]

In [66]:

symptoms = "itching, skin_rash"

user_symptoms = [s.strip() for s in symptoms.split(',')]
user_symptoms = [sym.strip("'[]' ") for sym in user_symptoms]
predicted_disease = get_predicted_value(user_symptoms)
desc,pre,med,die,wrkout = helper(predicted_disease)

print("=================predicted disease============")
print(predicted_disease)
print("=================description==================")
print(desc)
print("=================precautions==================")
i = 1
for p_i in pre[0]:
    print(i, ": ", p_i)
    i += 1
i=1
print("=================medications==================")
for m_i in med:
    print(i, ": ", m_i)
    i += 1
i=1
print("=================workout==================")
for w_i in wrkout:
    print(i, ": ", w_i)
    i += 1
i=1
print("=================diets==================")
for d_i in die:
    print(i, ": ", d_i)
    i += 1

=================predicted disease============
Fungal infection
=================description==================
Fungal infection is a common skin condition caused by fungi.
=================precautions==================
1 :  bath twice
2 :  use detol or neem in bathing water
3 :  keep infected area dry
4 :  use clean cloths
=================medications==================
1 :  ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']
=================workout==================
1 :  Avoid sugary foods
2 :  Consume probiotics
3 :  Increase intake of garlic
4 :  Include yogurt in diet
5 :  Limit processed foods
6 :  Stay hydrated
7 :  Consume green tea
8 :  Eat foods rich in zinc
9 :  Include turmeric in diet
10 :  Eat fruits and vegetables
=================diets==================
1 :  ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']


c:\Users\abdul\OneDrive\Desktop\mlProjects\Full Stack Medicine recommendation\microservices\newenv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [56]:
description  = df_desc[df_desc["Disease"]== predicted_disease]['Description']


description = [w for w in description]


# Array mein data chahiye taaki hum usse map kr payenge


precaution = df_prec[df_prec["Disease"]== predicted_disease][["Precaution_1","Precaution_2"	,"Precaution_3","Precaution_4"]]

preccaution = [col for col in precaution.values]
preccaution

[array(['bath twice', 'use detol or neem in bathing water',
        'keep infected area dry', 'use clean cloths'], dtype=object)]

In [67]:
import sklearn
print(sklearn.__version__)

1.3.2
